#ifndef FLASH_LAYOUT_H
#define FLASH_LAYOUT_H

#include <stdint.h>

#define FLASH_BASE_ADDRESS        0x08000000UL
#define BOOTLOADER_SIZE_BYTES     (32UL * 1024UL)

#define SIGNED_IMAGE_BASE         0x08008000UL
#define SIGNED_MANIFEST_SIZE      96UL
#define SIGNATURE_ADDRESS         (SIGNED_IMAGE_BASE + 0x60UL)

#define APPLICATION_BASE_ADDRESS  0x08008200UL
#define APPLICATION_FLASH_END     0x08100000UL

#define MAX_PAYLOAD_SIZE \
    (APPLICATION_FLASH_END - APPLICATION_BASE_ADDRESS)

#endif
