#ifndef FLASH_LAYOUT_H
#define FLASH_LAYOUT_H
#include "board.h"

#include <stdint.h>

#define FLASH_BASE_ADDRESS        BOARD_FLASH_BASE
#define BOOTLOADER_SIZE_BYTES     BOARD_BOOTLOADER_SIZE

#define SIGNED_IMAGE_BASE         BOARD_SIGNED_IMAGE_BASE
#define SIGNED_MANIFEST_SIZE      96UL
#define SIGNATURE_ADDRESS         (SIGNED_IMAGE_BASE + 0x60UL)

#define APPLICATION_BASE_ADDRESS  BOARD_APPLICATION_BASE
#define APPLICATION_FLASH_END     0x08100000UL

#define MAX_PAYLOAD_SIZE \
    (APPLICATION_FLASH_END - APPLICATION_BASE_ADDRESS)

#endif
