#ifndef FLASH_LAYOUT_H
#define FLASH_LAYOUT_H
#include "board.h"

#include <stdint.h>

#define FLASH_BASE_ADDRESS        BOARD_FLASH_BASE
#define BOOTLOADER_SIZE_BYTES     BOARD_BOOTLOADER_SIZE

#define SIGNED_IMAGE_BASE         BOARD_SIGNED_IMAGE_BASE
#define SIGNED_MANIFEST_SIZE      STM32F429_SIGNED_MANIFEST_SIZE
#define SIGNATURE_ADDRESS         STM32F429_SIGNATURE_BASE

#define APPLICATION_BASE_ADDRESS  BOARD_APPLICATION_BASE
#define APPLICATION_FLASH_END     STM32F429_APPLICATION_FLASH_END
#define APPLICATION_MIN_SIZE      STM32F429_APPLICATION_MIN_PAYLOAD_SIZE
#define APPLICATION_MSP_BASE      STM32F429_APPLICATION_MSP_BASE
#define APPLICATION_MSP_END       STM32F429_APPLICATION_MSP_END
#define APPLICATION_MSP_ALIGNMENT STM32F429_APPLICATION_MSP_ALIGNMENT
#define SIGNED_IMAGE_FLAGS_ALLOWED_MASK \
    STM32F429_SIGNED_IMAGE_FLAGS_ALLOWED_MASK

#define MAX_PAYLOAD_SIZE          STM32F429_APPLICATION_PAYLOAD_MAX_SIZE

#endif
