#ifndef IMAGE_POLICY_H
#define IMAGE_POLICY_H

#define SIGNED_IMAGE_MAGIC     0x31474953UL
#define SIGNED_HEADER_VERSION  1UL
#define UPDATE_PACKAGE_FORMAT_VERSION 2UL
#define UPDATE_PACKAGE_TARGET_STM32F429IGT6_AB_V1 0xF429AB01UL
#define UPDATE_PACKAGE_IMAGE_TYPE_APPLICATION 1UL
#define MIN_IMAGE_VERSION      2UL

#endif
