#!/usr/bin/env python3
"""Run selected C host suites with gcov and summarize line/branch coverage."""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess  # nosec B404
from pathlib import Path
from typing import Any, cast

ROOT = Path(__file__).resolve().parents[1]
SUITES = (ROOT / "tests" / "update_protocol", ROOT / "tests" / "update_storage")
FILE_RE = re.compile(r"File '([^']+)'\n(.*?)(?=\nFile |\Z)", re.DOTALL)
METRIC_RE = re.compile(r"(Lines executed|Branches executed|Taken at least once):"
                       r"(\d+(?:\.\d+)?)% of (\d+)")


def run_suite(suite: Path) -> str:
    # Fixed local make argv; shell execution is disabled (Bandit B603/B607).
    completed = subprocess.run(  # nosec
        ["make", "clean", "test", "COVERAGE=1"],
        cwd=suite,
        capture_output=True,
        text=True,
        check=False,
    )
    if completed.returncode != 0:
        raise RuntimeError(f"coverage suite failed: {suite}\n{completed.stdout}{completed.stderr}")
    return completed.stdout + completed.stderr


def collect_suite(suite: Path) -> dict[str, object]:
    gcda_files = sorted((suite / "build").glob("*.gcda"))
    if not gcda_files:
        raise RuntimeError(f"no gcda files produced by {suite}")
    # Fixed local gcov argv; shell execution is disabled (Bandit B603/B607).
    completed = subprocess.run(  # nosec
        ["gcov", "-b", "-c", "-o", str(suite / "build"), *map(str, gcda_files)],
        cwd=suite,
        capture_output=True,
        text=True,
        check=False,
    )
    if completed.returncode != 0:
        raise RuntimeError(f"gcov failed for {suite}\n{completed.stdout}{completed.stderr}")
    output = completed.stdout + completed.stderr
    for generated in suite.glob("*.gcov"):
        generated.unlink()
    files: list[dict[str, Any]] = []
    for filename, block in FILE_RE.findall(output):
        metrics: dict[str, tuple[float, int]] = {}
        for metric, percent, total in METRIC_RE.findall(block):
            metrics[metric] = (float(percent), int(total))
        files.append({"file": filename, "metrics": metrics})

    def is_project_file(filename: str) -> bool:
        excluded = ("monocypher", "test_", "simulated_flash", "performance_stub", ".h.gcov")
        return not any(part in filename for part in excluded)

    def aggregate(names: tuple[str, ...] | None = None) -> dict[str, Any]:
        selected = [
            item for item in files
            if is_project_file(str(item["file"]))
            and (names is None or any(name in str(item["file"]) for name in names))
        ]
        line_done = line_total = 0.0
        branch_done = branch_total = 0.0
        taken_done = taken_total = 0.0
        for item in selected:
            metrics = item["metrics"]
            line = metrics.get("Lines executed")
            branch = metrics.get("Branches executed")
            taken = metrics.get("Taken at least once")
            if line is not None:
                line_done += line[0] * line[1] / 100.0
                line_total += line[1]
            if branch is not None:
                branch_done += branch[0] * branch[1] / 100.0
                branch_total += branch[1]
            if taken is not None:
                taken_done += taken[0] * taken[1] / 100.0
                taken_total += taken[1]
        return {
            "line_percent": round(100.0 * line_done / line_total, 2) if line_total else None,
            "branch_percent": round(100.0 * branch_done / branch_total, 2) if branch_total else None,
            "branches_taken_percent": round(100.0 * taken_done / taken_total, 2)
            if taken_total else None,
        }

    project = aggregate()
    critical = aggregate(("boot_metadata.c", "boot_slot_selection.c", "update_package.c", "update_protocol.c"))
    return {
        "suite": str(suite.relative_to(ROOT)),
        "gcda_files": len(gcda_files),
        "project": project,
        "critical_policy_and_parser": critical,
        "files": files,
        "gcov_output": output,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--json-output", type=Path, default=ROOT / "coverage" / "c-coverage.json")
    parser.add_argument("--markdown-output", type=Path, default=ROOT / "coverage" / "c-coverage.md")
    args = parser.parse_args()

    if shutil.which("gcov") is None:
        raise SystemExit("gcov is not installed")
    results = []
    for suite in SUITES:
        run_suite(suite)
        results.append(collect_suite(suite))

    report = {"tool": "gcov", "suites": results}
    args.json_output.parent.mkdir(parents=True, exist_ok=True)
    args.json_output.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    markdown = ["# C host coverage", "", "Generated by `tools/collect_c_coverage.py`.", ""]
    for result in results:
        project = cast(dict[str, Any], result["project"])
        critical = cast(dict[str, Any], result["critical_policy_and_parser"])
        markdown.append(
            f"- `{result['suite']}`: project line {project['line_percent']}%, "
            f"branch {project['branch_percent']}%; critical parser/policy line "
            f"{critical['line_percent']}%, branch {critical['branch_percent']}%"
        )
    args.markdown_output.parent.mkdir(parents=True, exist_ok=True)
    args.markdown_output.write_text("\n".join(markdown) + "\n", encoding="utf-8")
    print(json.dumps(report, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
